### PR TITLE
Feature: Images

### PR DESCRIPTION
**Pull request by Nosajool**
Why didn't I just split this into an image upload commit and a code commit? gg and good luck @AcroMace 
#15

### CODE REVIEW

**Comment by Nosajool** [comment]
Split it up so that there aren't 1.5k images in one folder

**Comment by Nosajool** [comment]
skins are in

**Comment by AcroMace** [comment]
@Nosajool Is it really a good idea to store all of these locally instead of fetching them from another server?

**Comment by Nosajool** [comment]
Not sure where they would be located. The api FAQ says that they are working for a solution for getting images but it's not implemented yet.

**Comment by AcroMace** [comment]
@Nosajool You can technically hotlink them, not sure if that's a good idea though, especially if a way to use the API is coming

**Comment by Nosajool** [comment]
We'll see how slow it is on heroku

**Pull request merged**
