### PR TITLE
Fixer: Get that under 300 mb

### LINKED ISSUE #28: Get project size to < 300 mb
Don't want to `asset_sync`to aws yet so will just get under 300 mb.

Remove splash pictures and just use the battle ones where they were originally.

### PR DESCRIPTION
**Pull request by Nosajool**
Fixes #28 

@AcroMace used a bash command to get rid of all files with _Splash_ and that chopped off 150 mb of images that weren't really being used. Also got rid of screenshots since they were also taking space.

### CODE REVIEW

**Comment by AcroMace** [comment]
@Nosajool Weren't the splashes being used in the champion screens? Does the page still work without them?

**Comment by Nosajool** [comment]
@AcroMace second commit

**Comment by Nosajool** [comment]
dammit this is dev not master, oh well double merge

**Comment by AcroMace** [comment]
No

**Pull request closed without merging**
