### PR TITLE
Feature: Battle Version 2

### PR DESCRIPTION
**Pull request by Nosajool**
In this pull:
- Movespeed Order
- Level and Experience gain
- Armor and Magic Resist Calculation
- Database Logging
- New Targetting System as described in the [spec](https://github.com/Nosajool/League-Of-Valor/wiki/Battle)

@AcroMace It currently just spits out information about the battle (does not look too pretty) but the mechanics are all there. Got any ideas of how we are going to display the logs? Running a team of lvl 100's vs lvl 1's took 3 turns and running lvl 1's vs lvl 1's took 8 turns so don't worry about huge logs.

### CODE REVIEW

**Comment by AcroMace** [comment]
Waiting on @Nosajool reformatting the logging system to improve efficiency before merge.

**Comment by Nosajool** [comment]
@AcroMace Request has been granted.

**Comment by AcroMace** [comment]
LGTM :dancers:

**Comment by Nosajool** [comment]
restored?

**Comment by AcroMace** [comment]
I think when I deleted the branch from the GitHub app it automatically tried to delete the remote branch. Since the branch was already deleted it restored it so that it could delete it.

**Pull request merged**
